import {
  buildOptions,
  checkboxField,
  informedField,
  operatorCommentField,
  radioField,
  resultField,
  runSelectField,
  selectField,
  timelineFields,
} from "../sharedFields";

export default {
  id: "dosing_material",
  accent: "#C05D1E",
  title: "DOSIERUNG / MATERIAL",
  description:
    "Erfassen Sie hier alle Ereignisse rund um Dosierung, Rohstoffe, Chargen und Materialauffälligkeiten. Diese Informationen helfen, Zusammenhänge zwischen Material, Prozess und späteren Qualitätsproblemen zu erkennen.",
  submitLabel: "Jetzt erfassen",
  layout: [
    ["production_run", "event_time"],
    ["problem_first_occurred", "problem_noticed", "problem_resolved"],
    ["duration_before_discovery", "duration_resolution", "record_type"],
    [
      "affected_dosing_units",
      "affected_material",
      "affected_batch",
      "observations",
    ],
    [
      "material_anomalies",
      "observed_effects",
      "measures_taken",
      "adjusted_areas",
    ],
    [
      "suspected_cause",
      "production_impact",
      "informed_persons",
      "result",
    ],
    ["comment"],
  ],
  fields: [
    runSelectField(),
    ...timelineFields(),

    radioField(
      "record_type",
      "Was möchten Sie erfassen?",
      buildOptions([
        ["material_change", "Materialwechsel"],
        ["batch_change", "Chargenwechsel"],
        ["dosing_deviation", "Dosierabweichung"],
        ["material_anomaly", "Materialauffälligkeit"],
        ["recipe_change", "Rezepturänderung"],
        ["dosing_unit_malfunction", "Dosierer-Störung"],
        ["new_material_batch", "Neue Materialcharge"],
        ["other", "Sonstiges"],
      ]),
      { otherTextKey: "record_type_other" },
    ),

    checkboxField(
      "affected_dosing_units",
      "Welcher Dosierer ist betroffen?",
      buildOptions([
        ["eps", "EPS"],
        ["pentane", "Pentan"],
        ["nitrogen", "Stickstoff"],
        ["graphite", "Graphit"],
        ["recyclate", "Rezyklat"],
        ["off_spec", "OFF-Spec"],
        ["series_600", "600er-Reihe"],
        ["other_dosing_unit", "Anderer Dosierer"],
        ["other", "Sonstiges"],
      ]),
      { otherTextKey: "dosing_units_other" },
    ),

    selectField("affected_material", "Welches Material ist betroffen?", {
      optionsSource: "materials",
      placeholder: "Material auswählen",
      allowOther: true,
      otherTextKey: "affected_material_other",
    }),

    selectField("affected_batch", "Welche Charge ist betroffen?", {
      optionsSource: "batches",
      placeholder: "Charge auswählen",
      flags: [{ id: "unknown", label: "Unbekannt" }],
    }),

    checkboxField(
      "observations",
      "Was wurde beobachtet?",
      buildOptions([
        ["dosing_unit_not_regulating", "Dosierer regelt nicht sauber"],
        ["dosing_quantity_too_high", "Dosiermenge zu hoch"],
        ["dosing_quantity_too_low", "Dosiermenge zu niedrig"],
        ["material_flow_uneven", "Materialfluss ungleichmäßig"],
        ["trend_fluctuating", "Trend schwankt"],
        ["alarm", "Alarm"],
        ["material_empty", "Material leer"],
        ["material_bridge", "Materialbrücke"],
        ["conveying_problem", "Förderproblem"],
        ["no_anomaly", "Keine Auffälligkeit"],
        ["other", "Sonstiges"],
      ]),
      { otherTextKey: "observations_other" },
    ),

    checkboxField(
      "material_anomalies",
      "Materialauffälligkeiten",
      buildOptions([
        ["material_moist", "Material feucht"],
        ["material_dry", "Material trocken"],
        ["material_sticky", "Material klebrig"],
        ["dust", "Staub"],
        ["foreign_bodies", "Fremdkörper"],
        ["different_color", "Andere Farbe"],
        ["different_grain_size", "Andere Korngröße"],
        ["different_odor", "Anderer Geruch"],
        ["foams_differently", "Schäumt anders"],
        ["poor_flowability", "Schlechte Rieselfähigkeit"],
        ["other", "Sonstiges"],
      ]),
      { otherTextKey: "material_anomalies_other" },
    ),

    checkboxField(
      "observed_effects",
      "Welche Auswirkungen wurden beobachtet?",
      buildOptions([
        ["scrap", "Ausschuss"],
        ["pressure_rising", "Druck steigt"],
        ["pressure_falling", "Druck fällt"],
        ["torque_rising", "Drehmoment steigt"],
        ["torque_falling", "Drehmoment fällt"],
        ["temperature_changed", "Temperatur verändert"],
        ["poor_foaming_behavior", "Schlechtes Schäumverhalten"],
        ["cell_structure_changed", "Zellstruktur verändert"],
        ["fire_behavior_changed", "Brandverhalten verändert"],
        ["poor_quality", "Schlechte Qualität"],
        ["production_stop", "Produktionsstopp"],
        ["no_effects", "Keine Auswirkungen"],
        ["other", "Sonstiges"],
      ]),
      { otherTextKey: "observed_effects_other" },
    ),

    checkboxField(
      "measures_taken",
      "Welche Maßnahme wurde durchgeführt?",
      buildOptions([
        ["material_changed", "Material gewechselt"],
        ["batch_changed", "Charge gewechselt"],
        ["dosing_adjusted", "Dosierung angepasst"],
        ["dosing_unit_restarted", "Dosierer neu gestartet"],
        ["material_refilled", "Material nachgefüllt"],
        ["production_reduced", "Produktion reduziert"],
        ["production_stopped", "Produktion gestoppt"],
        ["production_manager_informed", "Produktionsleiter informiert"],
        ["quality_informed", "Qualität informiert"],
        ["no_measure", "Keine Maßnahme"],
        ["other", "Sonstiges"],
      ]),
      { otherTextKey: "measures_taken_other" },
    ),

    checkboxField(
      "adjusted_areas",
      "Mussten weitere Bereiche angepasst werden?",
      buildOptions([
        ["extruder", "Extruder"],
        ["screen_changer", "Siebwechsler"],
        ["die", "Düse"],
        ["water_box", "Wasserbox"],
        ["granulator", "Granulator"],
        ["knives", "Messer"],
        ["quality_control", "Qualitätskontrolle"],
        ["none", "Keine"],
        ["other", "Sonstiges"],
      ]),
      { otherTextKey: "adjusted_areas_other" },
    ),

    checkboxField(
      "suspected_cause",
      "Vermutete Ursache",
      buildOptions([
        ["poor_material_quality", "Schlechte Materialqualität"],
        ["wrong_batch", "Falsche Charge"],
        ["dosing_unit_defective", "Dosierer defekt"],
        ["material_moisture", "Materialfeuchte"],
        ["material_stored_incorrectly", "Material falsch gelagert"],
        ["recipe_problem", "Rezepturproblem"],
        ["operator_error", "Bedienfehler"],
        ["raw_material_quality", "Rohstoffqualität"],
        ["unknown", "Unbekannt"],
        ["other", "Sonstiges"],
      ]),
      { otherTextKey: "suspected_cause_other" },
    ),

    checkboxField(
      "production_impact",
      "Auswirkungen auf die Produktion",
      buildOptions([
        ["none", "Keine"],
        ["production_speed_reduced", "Produktionsgeschwindigkeit reduziert"],
        ["quality_deviation", "Qualitätsabweichung"],
        ["scrap", "Ausschuss"],
        ["production_stop", "Produktionsstopp"],
        ["rework_required", "Nacharbeit erforderlich"],
        ["other", "Sonstiges"],
      ]),
      { otherTextKey: "production_impact_other" },
    ),

    informedField(),
    resultField(),

    operatorCommentField([
      "Was ist passiert?",
      "Was ist Ihnen zuerst aufgefallen?",
      "Warum haben Sie eingegriffen?",
      "Welche Maßnahme wurde durchgeführt?",
      "Hat sich der Prozess danach verbessert?",
      "Gibt es weitere Beobachtungen oder Empfehlungen?",
    ]),
  ],
};
