import {
  buildOptions,
  checkboxField,
  informedField,
  operatorCommentField,
  radioField,
  resultField,
  runSelectField,
  timelineFields,
} from "../sharedFields";

export default {
  id: "extruder",
  accent: "#8E4A1E",
  title: "EXTRUDER",
  description:
    "Erfassen Sie hier alle Ereignisse, Beobachtungen und Maßnahmen rund um den Extruder. Die Einträge helfen, Druck-, Temperatur- und Drehmomentänderungen zu verstehen und spätere Qualitäts- oder Produktionsprobleme frühzeitig zu erkennen.",
  submitLabel: "Jetzt erfassen",
  layout: [
    ["production_run", "event_time"],
    ["problem_first_occurred", "problem_noticed", "problem_resolved"],
    ["duration_before_discovery", "duration_resolution"],
    ["record_type", "affected_areas"],
    ["affected_process_values", "observations"],
    ["preceding_events", "detection_method"],
    ["observed_effects", "measures_taken"],
    ["adjusted_areas", "suspected_cause"],
    ["criticality", "scrap_amount"],
    ["production_impact", "informed_persons"],
    ["result", "earlier_intervention"],
    ["comment"],
  ],
  fields: [
    runSelectField(),
    ...timelineFields(),

    radioField(
      "record_type",
      "Was möchten Sie erfassen?",
      buildOptions([
        ["pressure_deviation", "Druckabweichung"],
        ["temperature_deviation", "Temperaturabweichung"],
        ["torque_deviation", "Drehmomentabweichung"],
        ["screw_speed_changed", "Schneckendrehzahl geändert"],
        ["extruder_malfunction", "Extruder-Störung"],
        ["process_instability", "Prozessinstabilität"],
        ["production_start", "Produktionsstart"],
        ["production_stop", "Produktionsstopp"],
        ["other", "Sonstiges"],
      ]),
      { otherTextKey: "record_type_other" },
    ),

    checkboxField(
      "affected_areas",
      "Welcher Bereich war betroffen?",
      buildOptions([
        ["screw", "Schnecke"],
        ["barrel", "Zylinder"],
        ["feed_zone", "Einzugszone"],
        ["compression_zone", "Kompressionszone"],
        ["discharge_zone", "Austragszone"],
        ["adapter", "Adapter"],
        ["heating_zone_1", "Heizzone 1"],
        ["heating_zone_2", "Heizzone 2"],
        ["heating_zone_3", "Heizzone 3"],
        ["heating_zone_4", "Heizzone 4"],
        ["heating_zone_5", "Heizzone 5"],
        ["heating_zone_6", "Heizzone 6"],
        ["other", "Sonstiges"],
      ]),
      { otherTextKey: "affected_areas_other" },
    ),

    checkboxField(
      "affected_process_values",
      "Welche Prozesswerte waren betroffen?",
      buildOptions([
        ["pressure", "Druck"],
        ["temperature", "Temperatur"],
        ["melt_temperature", "Massetemperatur"],
        ["torque", "Drehmoment"],
        ["screw_speed", "Schneckendrehzahl"],
        ["motor_load", "Motorlast"],
        ["energy_consumption", "Energieverbrauch"],
        ["throughput", "Durchsatz"],
        ["other", "Sonstiges"],
      ]),
      { otherTextKey: "affected_process_values_other" },
    ),

    checkboxField(
      "observations",
      "Was wurde beobachtet?",
      buildOptions([
        ["pressure_rising_slowly", "Druck steigt langsam"],
        ["pressure_rising_suddenly", "Druck steigt plötzlich"],
        ["pressure_falling", "Druck fällt"],
        ["pressure_fluctuating", "Druck schwankt"],
        ["temperature_rising", "Temperatur steigt"],
        ["temperature_falling", "Temperatur fällt"],
        ["temperature_fluctuating", "Temperatur schwankt"],
        ["torque_rising", "Drehmoment steigt"],
        ["torque_falling", "Drehmoment fällt"],
        ["torque_fluctuating", "Drehmoment schwankt"],
        ["process_unstable", "Prozess instabil"],
        ["material_building_up", "Materialablagerungen"],
        ["unusual_noise", "Ungewöhnliches Geräusch"],
        ["unusual_vibration", "Ungewöhnliche Vibration"],
        ["alarm_triggered", "Alarm ausgelöst"],
        ["no_anomaly", "Keine Auffälligkeit"],
        ["other", "Sonstiges"],
      ]),
      { otherTextKey: "observations_other" },
    ),

    checkboxField(
      "preceding_events",
      "Was ist unmittelbar davor passiert?",
      buildOptions([
        ["material_change", "Materialwechsel"],
        ["batch_change", "Chargenwechsel"],
        ["dosing_changed", "Dosierung geändert"],
        ["recipe_changed", "Rezeptur geändert"],
        ["production_start", "Produktionsstart"],
        ["restart", "Neustart"],
        ["cleaning", "Reinigung"],
        ["screen_change", "Siebwechsel"],
        ["die_changed", "Düse gewechselt"],
        ["knives_changed", "Messer gewechselt"],
        ["maintenance", "Wartung"],
        ["nothing", "Nichts"],
        ["other", "Sonstiges"],
      ]),
      { otherTextKey: "preceding_events_other" },
    ),

    checkboxField(
      "detection_method",
      "Wie wurde das Problem erkannt?",
      buildOptions([
        ["trend_detected", "Trend erkannt"],
        ["alarm", "Alarm"],
        ["quality_control", "Qualitätskontrolle"],
        ["visual_inspection", "Sichtkontrolle"],
        ["experience", "Erfahrung"],
        ["shift_supervisor", "Schichtführer"],
        ["production_manager", "Produktionsleiter"],
        ["other", "Sonstiges"],
      ]),
      { otherTextKey: "detection_method_other" },
    ),

    checkboxField(
      "observed_effects",
      "Welche Auswirkungen wurden beobachtet?",
      buildOptions([
        ["lumps", "Klumpen"],
        ["open_holes", "Offene Löcher"],
        ["twin_beads", "Zwillinge"],
        ["poor_particle_size_distribution", "Schlechte Korngrößenverteilung"],
        ["cell_structure_changed", "Zellstruktur verändert"],
        ["foam_changed", "Schaum verändert"],
        ["scrap", "Ausschuss"],
        ["production_output_reduced", "Produktionsleistung reduziert"],
        ["production_stop", "Produktionsstopp"],
        ["no_effects", "Keine Auswirkungen"],
        ["other", "Sonstiges"],
      ]),
      { otherTextKey: "observed_effects_other" },
    ),

    checkboxField(
      "measures_taken",
      "Welche Maßnahme wurde durchgeführt?",
      buildOptions([
        ["temperature_adjusted", "Temperatur angepasst"],
        ["screw_speed_adjusted", "Schneckendrehzahl angepasst"],
        ["production_speed_reduced", "Produktionsgeschwindigkeit reduziert"],
        ["dosing_adjusted", "Dosierung angepasst"],
        ["material_changed", "Material gewechselt"],
        ["batch_changed", "Charge gewechselt"],
        ["screen_changed", "Sieb gewechselt"],
        ["die_changed", "Düse gewechselt"],
        ["cleaning_performed", "Reinigung durchgeführt"],
        ["restart", "Neustart"],
        ["production_stopped", "Produktion gestoppt"],
        ["no_measure", "Keine Maßnahme"],
        ["other", "Sonstiges"],
      ]),
      { otherTextKey: "measures_taken_other" },
    ),

    checkboxField(
      "adjusted_areas",
      "Mussten weitere Bereiche angepasst werden?",
      buildOptions([
        ["dosing", "Dosierung"],
        ["screen_changer", "Siebwechsler"],
        ["die", "Düse"],
        ["water_box", "Wasserbox"],
        ["granulator", "Granulator"],
        ["knives", "Messer"],
        ["quality_control", "Qualitätskontrolle"],
        ["laboratory", "Labor"],
        ["none", "Keine"],
        ["other", "Sonstiges"],
      ]),
      { otherTextKey: "adjusted_areas_other" },
    ),

    checkboxField(
      "suspected_cause",
      "Vermutete Ursache",
      buildOptions([
        ["material_problem", "Materialproblem"],
        ["dosing_problem", "Dosierproblem"],
        ["recipe_problem", "Rezepturproblem"],
        ["temperature", "Temperatur"],
        ["pressure", "Druck"],
        ["torque", "Drehmoment"],
        ["technical_defect", "Technischer Defekt"],
        ["operator_error", "Bedienfehler"],
        ["wear", "Verschleiß"],
        ["unknown", "Unbekannt"],
        ["other", "Sonstiges"],
      ]),
      { otherTextKey: "suspected_cause_other" },
    ),

    radioField(
      "criticality",
      "Wie kritisch war das Problem?",
      buildOptions([
        ["no_impact", "Keine Auswirkung"],
        ["low", "Gering"],
        ["medium", "Mittel"],
        ["high", "Hoch"],
        ["production_downtime", "Produktionsstillstand"],
      ]),
    ),

    radioField(
      "scrap_amount",
      "Ausschuss",
      buildOptions([
        ["no_scrap", "Kein Ausschuss"],
        ["little", "Wenig"],
        ["medium", "Mittel"],
        ["a_lot", "Viel"],
        ["entire_batch", "Gesamte Charge"],
      ]),
    ),

    checkboxField(
      "production_impact",
      "Auswirkungen auf die Produktion",
      buildOptions([
        ["production_speed_reduced", "Produktionsgeschwindigkeit reduziert"],
        ["quality_deviation", "Qualitätsabweichung"],
        ["rework_required", "Nacharbeit erforderlich"],
        ["production_stop", "Produktionsstopp"],
        ["none", "Keine"],
        ["other", "Sonstiges"],
      ]),
      { otherTextKey: "production_impact_other" },
    ),

    informedField(),
    resultField(),

    radioField(
      "earlier_intervention",
      "Würden Sie beim nächsten Mal früher eingreifen?",
      buildOptions([
        ["yes", "Ja"],
        ["no", "Nein"],
        ["same_time", "Zum gleichen Zeitpunkt"],
        ["not_assessable", "Nicht beurteilbar"],
      ]),
    ),

    operatorCommentField([
      "Was ist passiert?",
      "Was ist Ihnen zuerst aufgefallen?",
      "Warum haben Sie eingegriffen?",
      "Welche Maßnahme war erfolgreich?",
      "Welche Empfehlung geben Sie dem nächsten Operator?",
    ]),
  ],
};
