import {
  buildOptions,
  checkboxField,
  informedField,
  operatorCommentField,
  radioField,
  resultField,
  runSelectField,
  timelineFields,
} from "../sharedFields";

const INFORMED_KEYS = [
  "nobody",
  "shift_supervisor",
  "production_manager",
  "maintenance",
  "quality_assurance",
  "other",
];

export default {
  id: "water_box",
  accent: "#458B42",
  title: "WASSERBOX (KÜHLUNG)",
  description:
    "Erfassen Sie hier alle Beobachtungen, Störungen und Eingriffe an der Wasserbox. Die Wasserbox sorgt für die Kühlung und Stabilisierung des Granulats – die Daten helfen, Zusammenhänge zwischen Kühlung, Prozessverhalten und späteren Qualitätsabweichungen zu erkennen.",
  submitLabel: "Jetzt erfassen",
  plantValues: [
    { id: "process_water_temperature", label: "Prozesswassertemperatur" },
    { id: "process_water_pressure", label: "Prozesswasserdruck" },
    { id: "water_flow_rate", label: "Wasserdurchflussmenge" },
    { id: "production_run", label: "Produktionslauf" },
    { id: "machine", label: "Maschine" },
    { id: "material", label: "Material" },
    { id: "recipe", label: "Rezeptur" },
  ],
  layout: [
    ["production_run", "event_time"],
    ["problem_first_occurred", "problem_noticed", "problem_resolved"],
    ["duration_before_discovery", "duration_resolution"],
    ["record_type", "observations"],
    ["abnormal_plant_values", "preceding_events"],
    ["measures_taken", "suspected_cause"],
    ["adjusted_areas", "informed_persons"],
    ["result"],
    ["comment"],
  ],
  fields: [
    runSelectField(),
    ...timelineFields(),

    radioField(
      "record_type",
      "Was möchten Sie erfassen?",
      buildOptions([
        ["water_box_inspected", "Wasserbox kontrolliert"],
        ["cooling_problem", "Kühlproblem"],
        ["water_pressure_problem", "Wasserdruckproblem"],
        ["water_temperature_problem", "Wassertemperaturproblem"],
        ["water_flow_problem", "Wasserdurchflussproblem"],
        ["leak", "Leckage"],
        ["cleaning", "Reinigung"],
        ["maintenance", "Wartung"],
        ["other", "Sonstiges"],
      ]),
      { otherTextKey: "record_type_other" },
    ),

    checkboxField(
      "observations",
      "Was wurde beobachtet?",
      buildOptions([
        ["water_temperature_too_high", "Wassertemperatur zu hoch"],
        ["water_temperature_too_low", "Wassertemperatur zu niedrig"],
        ["water_pressure_too_low", "Wasserdruck zu niedrig"],
        ["water_pressure_too_high", "Wasserdruck zu hoch"],
        ["water_pressure_fluctuating", "Wasserdruck schwankt"],
        ["water_flow_reduced", "Wasserdurchfluss reduziert"],
        ["no_water_flow", "Kein Wasserdurchfluss"],
        ["water_contaminated", "Wasser verschmutzt"],
        ["air_bubbles_in_water", "Luftblasen im Wasser"],
        ["foam_formation", "Schaumbildung"],
        ["leak", "Leckage"],
        ["unusual_noises", "Ungewöhnliche Geräusche"],
        ["unusual_vibrations", "Ungewöhnliche Vibrationen"],
        ["cooling_uneven", "Kühlung ungleichmäßig"],
        ["no_anomaly", "Keine Auffälligkeit"],
        ["other", "Sonstiges"],
      ]),
      { otherTextKey: "observations_other" },
    ),

    checkboxField(
      "abnormal_plant_values",
      "Welche Anlagenwerte waren auffällig?",
      buildOptions([
        ["process_water_temperature", "Prozesswassertemperatur"],
        ["process_water_pressure", "Prozesswasserdruck"],
        ["water_flow_rate", "Wasserdurchflussmenge"],
        ["cooling_performance", "Kühlleistung"],
        ["no_measured_values_abnormal", "Keine Messwerte auffällig"],
        ["other", "Sonstiges"],
      ]),
      { otherTextKey: "abnormal_plant_values_other" },
    ),

    checkboxField(
      "preceding_events",
      "Was ist unmittelbar davor passiert?",
      buildOptions([
        ["production_start", "Produktionsstart"],
        ["production_stop", "Produktionsstopp"],
        ["restart", "Neustart"],
        ["material_change", "Materialwechsel"],
        ["batch_change", "Chargenwechsel"],
        ["screen_change", "Siebwechsel"],
        ["die_change", "Düsenwechsel"],
        ["extruder_adjusted", "Extruder angepasst"],
        ["maintenance", "Wartung"],
        ["cleaning", "Reinigung"],
        ["nothing_special", "Nichts Besonderes"],
        ["other", "Sonstiges"],
      ]),
      { otherTextKey: "preceding_events_other" },
    ),

    checkboxField(
      "measures_taken",
      "Welche Maßnahme wurde durchgeführt?",
      buildOptions([
        ["water_pressure_adjusted", "Wasserdruck angepasst"],
        ["water_temperature_adjusted", "Wassertemperatur angepasst"],
        ["water_supply_checked", "Wasserzufuhr geprüft"],
        ["cooling_circuit_checked", "Kühlkreislauf geprüft"],
        ["filter_cleaned", "Filter gereinigt"],
        ["leak_repaired", "Leckage behoben"],
        ["valve_checked", "Ventil geprüft"],
        ["pump_checked", "Pumpe geprüft"],
        ["production_reduced", "Produktion reduziert"],
        ["production_stopped", "Produktion gestoppt"],
        ["maintenance_informed", "Instandhaltung informiert"],
        ["no_measure", "Keine Maßnahme"],
        ["other", "Sonstiges"],
      ]),
      { otherTextKey: "measures_taken_other" },
    ),

    checkboxField(
      "suspected_cause",
      "Vermutete Ursache",
      buildOptions([
        ["cooling_water_too_warm", "Kühlwasser zu warm"],
        ["cooling_water_too_cold", "Kühlwasser zu kalt"],
        ["water_pressure_too_low", "Wasserdruck zu niedrig"],
        ["water_pressure_too_high", "Wasserdruck zu hoch"],
        ["pump", "Pumpe"],
        ["valve", "Ventil"],
        ["filter_contaminated", "Filter verschmutzt"],
        ["line_blocked", "Leitung verstopft"],
        ["leak", "Leckage"],
        ["technical_defect", "Technischer Defekt"],
        ["operator_error", "Bedienfehler"],
        ["unknown", "Unbekannt"],
        ["other", "Sonstiges"],
      ]),
      { otherTextKey: "suspected_cause_other" },
    ),

    checkboxField(
      "adjusted_areas",
      "Mussten weitere Bereiche angepasst werden?",
      buildOptions([
        ["dosing", "Dosierung"],
        ["extruder", "Extruder"],
        ["screen_changer", "Siebwechsler"],
        ["die", "Düse"],
        ["granulator", "Granulator"],
        ["knives", "Messer"],
        ["quality_control_informed", "Qualitätskontrolle informiert"],
        ["none", "Keine"],
        ["other", "Sonstiges"],
      ]),
      { otherTextKey: "adjusted_areas_other" },
    ),

    informedField(INFORMED_KEYS),
    resultField(),

    operatorCommentField([
      "Was wurde an der Wasserbox beobachtet?",
      "Warum wurde eingegriffen?",
      "Welche Maßnahme wurde durchgeführt?",
      "Was hat sich nach der Maßnahme verändert?",
      "Gibt es Hinweise für die nächste Schicht?",
    ]),
  ],
};
